In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import datetime as dt
from sklearn.preprocessing import OneHotEncoder

In [2]:
df = pd.read_csv('../data/data-clean-20220916.01.csv')

In [3]:
df['Start_Time']= pd.to_datetime(df['Start_Time'])

In [4]:
df['day'] = df['Start_Time'].dt.day
df['month'] = df['Start_Time'].dt.month
df['year'] = df['Start_Time'].dt.year
df['hour'] = df['Start_Time'].dt.hour

In [5]:
df.head()

,Severity,Start_Time,Start_Lat,Start_Lng,Side,State,Timezone,Temperature(F),Humidity(%),Pressure(in),...,wc_snow,wc_thunder,wc_wind,st_interstate,st_highway,st_other,day,month,year,hour
0,1,2016-02-08 00:37:08,40.108910,-83.092860,R,OH,US/Eastern,42.1,58.0,29.76,...,0,0,0,0,0,1,8,2,2016,0
1,0,2016-02-08 05:56:20,39.865420,-84.062800,R,OH,US/Eastern,36.9,91.0,29.68,...,0,0,0,1,0,0,8,2,2016,5
2,0,2016-02-08 06:15:39,39.102660,-84.524680,R,OH,US/Eastern,36.0,97.0,29.70,...,0,0,0,1,0,0,8,2,2016,6
3,0,2016-02-08 06:51:45,41.062130,-81.537840,R,OH,US/Eastern,39.0,55.0,29.65,...,0,0,0,1,0,0,8,2,2016,6
4,1,2016-02-08 07:53:43,39.172393,-84.492792,R,OH,US/Eastern,37.0,93.0,29.69,...,0,0,0,1,0,0,8,2,2016,7

In [6]:
df = pd.concat([df, pd.get_dummies(df['State'], prefix='State')], axis=1)
df = pd.concat([df, pd.get_dummies(df['Side'], prefix='Side')], axis=1)
df = pd.concat([df, pd.get_dummies(df['Timezone'], prefix='Timezone')], axis=1)
df = pd.concat([df, pd.get_dummies(df['year'], prefix='year')], axis=1)
df = pd.concat([df, pd.get_dummies(df['month'], prefix='month')], axis=1)
df = pd.concat([df, pd.get_dummies(df['hour'], prefix='hour')], axis=1)

#drop the columns: State, Side, Timezone, year, month, hour
df = df.drop(['State', 'Side', 'Timezone', 'year', 'month', 'hour'], axis=1)

In [7]:
[col for col in df.columns]

['Severity',
 'Start_Time',
 'Start_Lat',
 'Start_Lng',
 'Temperature(F)',
 'Humidity(%)',
 'Pressure(in)',
 'Visibility(mi)',
 'Wind_Speed(mph)',
 'Precipitation(in)',
 'Amenity',
 'Bump',
 'Crossing',
 'Give_Way',
 'Junction',
 'No_Exit',
 'Railway',
 'Roundabout',
 'Station',
 'Stop',
 'Traffic_Calming',
 'Traffic_Signal',
 'Sunrise_Sunset',
 'wc_clouds',
 'wc_dust',
 'wc_fair',
 'wc_fog',
 'wc_ice',
 'wc_rain',
 'wc_snow',
 'wc_thunder',
 'wc_wind',
 'st_interstate',
 'st_highway',
 'st_other',
 'day',
 'State_AL',
 'State_AR',
 'State_AZ',
 'State_CA',
 'State_CO',
 'State_CT',
 'State_DC',
 'State_DE',
 'State_FL',
 'State_GA',
 'State_IA',
 'State_ID',
 'State_IL',
 'State_IN',
 'State_KS',
 'State_KY',
 'State_LA',
 'State_MA',
 'State_MD',
 'State_ME',
 'State_MI',
 'State_MN',
 'State_MO',
 'State_MS',
 'State_MT',
 'State_NC',
 'State_ND',
 'State_NE',
 'State_NH',
 'State_NJ',
 'State_NM',
 'State_NV',
 'State_NY',
 'State_OH',
 'State_OK',
 'State_OR',
 'State_PA',
 'State_RI',
 'State_SC',
 'State_SD',
 'State_TN',
 'State_TX',
 'State_UT',
 'State_VA',
 'State_VT',
 'State_WA',
 'State_WI',
 'State_WV',
 'State_WY',
 'Side_L',
 'Side_R',
 'Timezone_US/Central',
 'Timezone_US/Eastern',
 'Timezone_US/Mountain',
 'Timezone_US/Pacific',
 'year_2016',
 'year_2017',
 'year_2018',
 'year_2019',
 'year_2020',
 'year_2021',
 'month_1',
 'month_2',
 'month_3',
 'month_4',
 'month_5',
 'month_6',
 'month_7',
 'month_8',
 'month_9',
 'month_10',
 'month_11',
 'month_12',
 'hour_0',
 'hour_1',
 'hour_2',
 'hour_3',
 'hour_4',
 'hour_5',
 'hour_6',
 'hour_7',
 'hour_8',
 'hour_9',
 'hour_10',
 'hour_11',
 'hour_12',
 'hour_13',
 'hour_14',
 'hour_15',
 'hour_16',
 'hour_17',
 'hour_18',
 'hour_19',
 'hour_20',
 'hour_21',
 'hour_22',
 'hour_23']

In [8]:
df.to_csv('../data/ohe_data.csv')

In [9]:
df['Severity'].value_counts(normalize=True)

0    0.900065
1    0.099935
Name: Severity, dtype: float64